version: "3.9"
services:
  # NestJS Backend Service
  nest-backend:
    build:
      context: ./packages/nest-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_DATABASE=nestdb
    depends_on:
      - postgres
    command: >
      sh -c "npm run start:dev"

  # Angular Frontend Service
  angular-frontend:
    build:
      context: ./packages/angular-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    command: >
      sh -c "ng serve --host 0.0.0.0 --disable-host-check"  

  # PostgreSQL Database Service
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestdb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
